# Generated by Django 5.0.4 on 2024-12-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='year_of_incorporate',
            new_name='year_of_incorporation',
        ),
    ]
