# Generated by Django 5.0.4 on 2024-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_year_of_incorporate_company_year_of_incorporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
