# Generated by Django 5.0.4 on 2024-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_of_incorporation',
            field=models.IntegerField(null=True),
        ),
    ]
